config/routes.rb
Rails.application.routes.draw do

  get 'searches/new'

  get 'searches/create'

  get 'searches/show'

  resources :line_items
  resources :carts
  resources :searches
  devise_for :users

  resources :line_item
  resources :cart

  resources :charges
  
  # map.resources :cart
  # map.connect ":controller/:action/:id"
  #instructs rails ro route correctly

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'savings/index'

  get 'history/index'

  get 'recipe/index'

  get 'charges/new'

  get 'charges/create'

  get 'searches/index'

  get 'searches/show'

  get 'welcome/index'

  #match 'devise/cart/index' => 'cart#index', :as => :cart, via: [:get]

  root 'welcome#index'

  resources :products
  resources :categories
  resources :cart
  resources :savings
  resources :history
  resources :recipe
  resources :welcome

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_item(product_id)
    item = line_items.find_by_product_id(product_id)
    #product = products.find_by_title()
    #item = produc
    #item = items.find_by(product_id: product_id).first
    #item = items.find_by(product_id: product_params[:product][:product_id])
    if item
      item.quantity += 1
      save
    else
      item = line_items.build(product_id: product_id, quantity: 1)
      #cart.items << Line_Item.new(product_id: product_id, quantity: 1, cart_id: self.id)
    end
    item
  end

#trying_recipe_button
  def add_items_from_recipe(title)#array 
    item = line_items.find_by(title)
    if item
      item.quantity +=1
      save
    else
      item = line_items.build(product_id: product_id, quantity: 1)

    end
    item
  end

  # for loop iterating through all the line_items to add up for a cart subtotal
  def subtotal
    subtotal = 0
    line_items.each do |item|
      subtotal = subtotal + item.total_price
    end
    subtotal
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_item(product_id, line_items)
    line_items.delete(product_id)
    @cart = current_cart
    redirect_to @cart
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<style>
table, th, td {
   border: 1px solid black;
}
th, td {
    padding: 8px;
    text-align: left;
}
</style>
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="4">Cart Options</th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td>Cart ID: <%= cart.id%></td>
        <td><%= link_to 'Show', cart, :class => 'btn' %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart), :class => 'btn' %></td>
        <td><%= link_to 'Destroy', cart, :class => 'btn', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path, :class =>'btn' %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb

<p id="notice"><%= notice %></p>
<style>


table {
    font-family: 500 100% 'Helvetica Neue', Helvetica, Arial;
    border-collapse: collapse;
    width: 80%;
}

td, th {
    border: 0px solid #5ada55;
    text-align: left;
    padding: 15px;
}

.Proceed-to-Checkout-button {
  -webkit-border-radius: 28;
  -moz-border-radius: 28;
  border-radius: 28px;
  color: #fff !important;
  font: 500 130% 'Helvetica Neue', Helvetica, Arial;
  background-color: #2dcf4e;
  padding: 6px 8px 6px 8px;
  margin-top:8px;
  text-decoration: none;
  border: none !important;
  outline: none !important;

}

.Proceed-to-Checkout-button:hover {
  background: #24bd47;
  text-decoration: none;
}

.remove-item-button {
  -webkit-border-radius: 28;
  -moz-border-radius: 28;
  border-radius: 28px;
  color: #fff !important;
  font: 500 100% 'Helvetica Neue', Helvetica, Arial;
  background-color: #f94f4f;
  padding: 5px 6px 5px 6px;
  text-decoration: none;
  border: none !important;
  outline: none !important;
}

.remove-item-button :hover {
  background: #ce4242;
  text-decoration: none;
}

.searchbar{
    width: 200px;
    border: 2px solid #ccc;
    border-radius: 5px;
    font-size: 15px;
    background-color: white;
    padding: 5px 5px 5px 5px;
    margin-right: 5px;
    margin-bottom: 2px;
}

</style>

<div style="margin-left: 120px; margin-top: 30px; ">
<table id="line_items" style="margin-left: 80px;">
   <tr>
     <th style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">Picture</th>
     <th style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">Product</th>
     <th style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">Qty</th>
     <th style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">Unit Price</th>
     <th style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">Full Price</th>
   </tr>


   <%# This for loop displays all items in a session's(customer's) cart %>
   <% for item in @cart.line_items %>

     <tr class="<%= cycle :odd, :even %>">
        <td><%=image_tag(item.product.image_url, alt: 'white', height: 44, width: 66) %></td>  
        <td style="font: 500 120% 'Helvetica Neue', Helvetica, Arial;"><%= item.product.title if item.product%></td>
        <td style="font: 500 120% 'Helvetica Neue', Helvetica, Arial;"><%= item.quantity %> &times; </td>
        <td style="font: 500 120% 'Helvetica Neue', Helvetica, Arial;"><%= number_with_precision(item.product.price, :precision => 2) if item.product %></td>
        <td style="font: 500 120% 'Helvetica Neue', Helvetica, Arial;"><%= number_to_currency(item.total_price, :precision => 2) %></td>
        <%# Add a button to destroy a line item %>
        <td ><%= button_to "Remove Item", item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "remove-item-button" %></td>
     </tr>
    <% end %>
    
</table>
<div>


<div class="row" style="margin-top: 20px;">
<div>


  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <p><!-- Display the total price from the cart items-->
      <label class="Total" style="font: 500 150% 'Helvetica Neue', Helvetica, Arial;">
        <span>Items Total: <%= number_to_currency(@cart.subtotal) %>
        </span>
      </label>
    </p>
    <p><!-- Display the tax calculated from total price of the cart items-->
      <label class="tax" style="font: 500 150% 'Helvetica Neue', Helvetica, Arial;">
        <span>Tax 9.25%: <%= number_to_currency((@cart.subtotal) * 0.0925) %></span>
      </label>
    </p>
    <p><!-- Display tax plus total amount -->
      <label class="new total" style="font: 500 150% 'Helvetica Neue', Helvetica, Arial;">
        <span>Total with tax included: <%= number_to_currency(((@cart.subtotal) * 0.0925)+(@cart.subtotal)) %></span>
      </label>
    </p>
    
  </article>
  <!--set amount  equal to the cartsubtotal and proceed with stripe checkout-->
  <%= form_tag charges_path(amount: (((@cart.subtotal) * 0.0925)+(@cart.subtotal))) do %>
    <p style="font: 500 180% 'Helvetica Neue', Helvetica, Arial;">
      <!--User enters couponcode, code gets passed to ccontroller -->
      <%= label_tag(:couponCode, 'Coupon:') %>
      <%= text_field_tag(:couponCode)%>
    </p>
    <!-- Chekout box that user needs to fill out-->
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Items in your cart"
          data-amount=""
          data-billingAddress="true"
          data-shippingAddress="true"
          data-locale="auto">
    </script>
  <% end %>

</div>





