config/routes.rb
Rails.application.routes.draw do

  get 'searches/new'

  get 'searches/create'

  get 'searches/show'

  resources :line_items
  resources :carts
  resources :searches
  devise_for :users

  resources :line_item
  resources :cart

  resources :charges
  
  # map.resources :cart
  # map.connect ":controller/:action/:id"
  #instructs rails ro route correctly

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'savings/index'

  get 'history/index'

  get 'recipe/index'

  get 'charges/new'

  get 'charges/create'

  get 'searches/index'

  get 'searches/show'

  get 'welcome/index'

  #match 'devise/cart/index' => 'cart#index', :as => :cart, via: [:get]

  root 'welcome#index'

  resources :products
  resources :categories
  resources :cart
  resources :savings
  resources :history
  resources :recipe
  resources :welcome

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  #ADDED dependency to line_items and a method
  has_many :line_items
  

  before_destroy :ensure_not_referenced_by_any_line_item

  def self.search(search)
    if search
      self.where("title like ?", "%#{search}%")
    else
      self.all
    end
  end

  #ADDED a private method
  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items Present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = Product.search(params[:search])
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @page_title = 'Add Book'
    @product = Product.new
    @category = Category.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=begin
  private 
    def book_params
    params.require(:product).permit(:title, :category_id, :description, :image_url, :price)
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :category_id, :description, :recipes, :recipe_instructions, :recipe_ingredients, :recipe_url, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>
<%# **************************CATEGORY******************************
    Category is a VERY important detail that allows one to pick from
    predetermined categories. So we can use this to sort by category
    eventually. YES SO HOPEFUL.
    ****************************************************************  %>
  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.collect {|x| [x.name, x.id]},
        {:include_blank => 'Select One'} %><br /><br />
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 6, id: :product_description %>
  </div>


  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

   <div class="field">
    <%= form.label :recipe_Title%>
    <%= form.text_area :recipes, rows: 2, id: :product_recipes %>
  </div>

 <div class="field">
    <%= form.label :recipe_Ingredients%>
    <%= form.text_area :recipe_ingredients, rows: 6, id: :product_recipe_ingredients %>
  </div>

 <div class="field">
    <%= form.label :recipe_Instructions%>
    <%= form.text_area :recipe_instructions, rows: 6, id: :product_recipe_instructions %>
  </div>

    <div class="field">
    <%= form.label :recipe_url %>
    <%= form.text_field :recipe_url, id: :product_recipe_url %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 

app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.title, product, :class =>'btn' %></h2>
  <%= link_to image_tag(product.image_url, alt: product.title, height: 200, width: 300), product %>

  <div class="details">
    <%= number_to_currency(product.price) %>
    <% if product.category %>
      | Category: <%= product.category.name %>
    <% end %>
  </div>
  
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<style type="text/css">
  .title {
    font-size: 14pt;
    font-weight: bold;
    margin-bottom: 16px;
  }
 .price{
   font-weight: 400;
   font-size: 12pt;
   text-align:right;
 }

</style>
<%# ***************Items Grid form *****************
    From 7 Creating Books(Products) YouTube video
    - Due to it being the products index,
    - This should be a loop to display all products
    - in rows of 3
    ************************************************ %>
<div id="products.index">
  <% @products.each_slice(3) do |product| %>
    <div class="row">
            <% product.each do |product| %>
        <div class="card-container">
        <div class="shadowed-card">
          
          <%= link_to image_tag(product.image_url, alt: product.title, height: 200, width: 300), product %>

          <div class="column profuct-into-font product-info" >
            <div class="title"><%= link_to product.title, product, :class =>"customized-btn" %></div>
            <div class="price"><%= number_to_currency product.price %></div>
          </div>

          <!-- <%= link_to 'Select', product_path(product), class:'button' %>   -->
          <div class="product-info" >
          <%= button_to 'Add to Cart', line_items_path(product_id: product), {:class => "add-to-cart-button" } %> 
          </div>

        </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>


<%#= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%# This is where we can see an individual product and it's info.
    NEXT to add here are suggestions in a div below.
 %>
<head>
<script type="text/javascript">
// Quantity spin buttons
function increase_by_one(field) {
 nr = parseInt(document.getElementById(field).value);
 document.getElementById(field).value = nr + 1;
}

function decrease_by_one(field) {
 nr = parseInt(document.getElementById(field).value);
 if (nr > 0) {
   if( (nr - 1) > 0) {
     document.getElementById(field).value = nr - 1;
   }
 }
}
</script>

<style type="text/css">
#qty1 { width: 30px; }

</style>
</head>

<style type="text/css">
.hmtl, body {
  height: 100%;
  width: 100%
  margin: 0;
  font-family: 'Roboto', sans-serif;
}
.container {
  margin-top: 200px
  max-width: 1200 px;
  padding: 15px;
  display: flex;
}
.left-column {
  width: 65%;
  margin-top: 50px;
  position: relative;
}
.right-column {
  width: 35%;
  margin-top: 60px;
}
.product-description{
  border-bottom: 1px solid #E1E8EE;
  margin-bottom: 20px;
}
.product-description span{
  font-size:12px;
  color: #358ED7;
  letter-spacing: 1px;
  text-transform: uppercase;
  text-decoration: none;
}
.product-description h1 {
  font-weight:300;
  font-size: 52px;
  color: #43484D;
  letter-spacing: -2px;
}
.product-description {
  font-size: 16px;
  font-weight: 300;
  color: #86939E;
  line-height: 24px;
}
.product-price{
  display: flex;
  align-items: center;
}
.product-price span{
  font-size:26px;
  font-weight: 300;
  color: #43474D;
  margin-right: 20px;
}
.cart-btn{
  display: inline-block;
  background-color: #7DC855;
  border-radius: 6px;
  font-size: 16px;
  color: #FFFFFF;
  text-decoration: none;
  padding: 12px 30px;
  transition: all .5s;
}
.cart-btn:hover {
  background-color: #64af3d:
}
.image-style{
  border-radius: 10px;
}

</style>
<main class="container">
  <!-- Left Column -->
  <div class="left-column">
    <div class="image"><%= image_tag(@product.image_url, alt: @product.title, height: 400, width: 600,)%>
    </div>
  </div>
  <!-- Right Column -->
  <div class="right-column">
    <div class="product-description">
      <span><%= @product.category.name %></span>
      <h1><%= @product.title %></h1>
      <p><%= @product.description %></p>
      <!--TO DO... -->
      <span>Recipe</span>
      <% if (@product.recipes.present?) then %>
      <p><b><%= @product.recipes %></b></p>
      <font color="green">Ingredients:</font>
      <p><%= @product.recipe_ingredients %></p>
      <font color="green">Instructions:</font>
      <p><%= @product.recipe_instructions %></p>
      <% end %>
      <% if (@product.recipe_url.present?) then %>
      <%= image_tag(@product.recipe_url, alt: @product.title, height: 140, width: 260, class:"image-style")%>
      <% end %>
      <p></p>
    </div>
    <div class="product-price">
      <span><%= number_to_currency @product.price %></span>
      <!-- <a href="#" class="cart-btn">Add to cart</a> -->
      <div class="product-info" >
        <%= button_to 'Add to Cart', line_items_path(product_id: @product), {:class => "add-to-cart-button" } %>
      </div>
      <div class="cart-quantity">
      	Qty: <input id="qty1" type="text" value="1" name="qty">
      	<button onclick="increase_by_one('qty1');">+</button>
      	<button onclick="decrease_by_one('qty1');">-</button>
    </div>
  </div>
</main>

<%#= link_to 'Edit', edit_product_path(@product) %> 
<%#= link_to 'Back', session[:return_to] = request.referer %>