config/routes.rb
Rails.application.routes.draw do

  get 'searches/new'

  get 'searches/create'

  get 'searches/show'

  resources :line_items
  resources :carts
  resources :searches
  devise_for :users

  resources :line_item
  resources :cart

  resources :charges
  
  # map.resources :cart
  # map.connect ":controller/:action/:id"
  #instructs rails ro route correctly

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'savings/index'

  get 'history/index'

  get 'recipe/index'

  get 'charges/new'

  get 'charges/create'

  get 'searches/index'

  get 'searches/show'

  get 'welcome/index'

  #match 'devise/cart/index' => 'cart#index', :as => :cart, via: [:get]

  root 'welcome#index'

  resources :products
  resources :categories
  resources :cart
  resources :savings
  resources :history
  resources :recipe
  resources :welcome

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_item(product_id)
    item = line_items.find_by_product_id(product_id)
    #product = products.find_by_title()
    #item = produc
    #item = items.find_by(product_id: product_id).first
    #item = items.find_by(product_id: product_params[:product][:product_id])
    if item
      item.quantity += 1
      save
    else
      item = line_items.build(product_id: product_id, quantity: 1)
      #cart.items << Line_Item.new(product_id: product_id, quantity: 1, cart_id: self.id)
    end
    item
  end

#trying_recipe_button
  def add_items_from_recipe(title)#array 
    item = line_items.find_by(title)
    if item
      item.quantity +=1
      save
    else
      item = line_items.build(product_id: product_id, quantity: 1)

    end
    item
  end

  # for loop iterating through all the line_items to add up for a cart subtotal
  def subtotal
    subtotal = 0
    line_items.each do |item|
      subtotal = subtotal + item.total_price
    end
    subtotal
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  def self.search(search)
    if search
      self.joins(:products).where("title like ?", "%#{search}%")
    else
      self.all
    end
  end

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :coupon
  validates_presence_of :amount, :stripe_id
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  has_many :charges
  validates_presence_of :code, :discount_percent
  validates_uniqueness_of :code

  def self.get(code)
    where(code: normalize_code(code)).
    take
  end
  def total
    return Cart.first.subtotal
  end
  def apply_discount(amount)
    discount = amount * (self.discount_percent * 0.01)
    (amount - discount.to_i)
  end

  def discount_percent_human
    if discount_percent.present?
      discount_percent.to_s + "%"
    end
  end

  private

  def self.normalize_code(code)
    code.gsub(/\s+/, '').upcase
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  #ADDED dependency to line_items and a method
  has_many :line_items
  

  before_destroy :ensure_not_referenced_by_any_line_item

  def self.search(search)
    if search
      self.where("title like ?", "%#{search}%")
    else
      self.all
    end
  end

  #ADDED a private method
  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items Present')
        return false
      end
    end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def result
      @result ||= find_result
  end

  private
      
    def find_result
      result = Product.all
      result = result.where("title like ?", "%#{keywords}%") if keywords.present?
      result = result.where("category_id == ?", category_id) if category_id.present?
      result = result.where("price >= ?", min_price) if min_price.present?
      result = result.where("price <= ?", max_price) if max_price.present?
      result
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_user
    :guest == false
  end

  def is_guest
    :guest == true
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_item(product_id, line_items)
    line_items.delete(product_id)
    @cart = current_cart
    redirect_to @cart
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

 
  def create
    @amount = params[:amount].to_f 
    @amount = @amount * 100
    @final_amount = @amount
    code = params[:couponCode]

  if !code.blank?
    @coupon = Coupon.get(code)

  if @coupon.nil?
    @final_amount= @amount
    @discount_amount = 00
    
    return
  else
    @final_amount = @coupon.apply_discount(@amount.to_i)
    @discount_amount = (@amount - @final_amount)
  end

  charge_metadata = {
    :coupon_code => @coupon.code,
    :coupon_discount => @coupon.discount_percent_human
  }
  end

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )
  stripe_charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @final_amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd',
    :metadata    => charge_metadata
  )
  @charge = Charge.create(amount: @final_amount, coupon: @coupon, stripe_id: stripe_charge.id)
  rescue Stripe::CardError => e
    flash[:error] = e.message
  end
 
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
  	 @products = Product.all
  end


   def show
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<style type="text/css">
  .searchbar{
    width: 200px;
    border: 2px solid #ccc;
    border-radius: 25px;
    font-size: 15px;
    background-color: white;
    padding: 5px 5px 5px 5px;
    margin-right: 5px;
  }

</style>
<html>
  <head>
    <title>HealthWay</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', "https://www.w3schools.com/w3css/4/w3.css", "https://www.w3schools.com/w3css/4/w3.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navigation-bar-backgroud fixed-top">

      <div class="navigation-bar-container">
        <div class="row">
          <%=image_tag('white.jpg', alt: 'white', height: 10, width: 25) %>
          <%= link_to 'HealthWay', root_path, :class => "healthway" %>
        </div>
        <div class="row slogen">
          <%=image_tag('white.jpg', alt: 'white', height: 10, width: 27) %>
          <h5>Eat healthier. Live longer.</h5>
        </div>
      </div>

      <!-- <a class="navbar-brand" href="#">Safeway</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%#= link_to ' About', about_path %>
          </li>
          <li class="nav-item active">
            <%#= link_to 'Shop', groceries_path %>
          </li>
          <!--<li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->
        </ul>

       <form class="form-inline my-2 my-lg-0">
          <%= form_tag searches_path, method: :get do %>
            <%= label_tag(:q, "") %>
            <%= text_field_tag(:search, params[:search], class: "searchbar")%>
            <%= link_to "Search", products_path, class: "customized-btn", method: :get%>
            <%= link_to "Advanced Search", new_search_path, class: "customized-btn", action: 'new' %>
          <% end %>

          <!--<input class="form-control mr-sm-2 navigation-bar-item" type="text" placeholder="Search" aria-label="Search">-->
          <%=image_tag('white.jpg', alt: 'white', height: 40, width: 35) %>

            <% if user_signed_in? %>
              <div class = "small-defaul-font">Logged in: <strong><%= current_user.email %></strong></div>
              <%=image_tag('white.jpg', alt: 'white', height: 10, width: 10) %>
              <button class="button" type="submit"><%= link_to 'Profile', edit_user_registration_path, :class => "small-button" %></button>
              <%=image_tag('white.jpg', alt: 'white', height: 40, width: 15) %>
              <button class="button" type="submit"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "small-button"%></button>
            <% else %>
              <button class="button" type="submit"><%= link_to "Sign up", new_user_registration_path, :class => "small-button" %></button>
              <%=image_tag('white.jpg', alt: 'white', height: 40, width: 15) %>
              <button class="button" type="submit"><%= link_to "Login", new_user_session_path, :class => "small-button" %></button>
            <% end %>

          <!--
          <button class="button" type="submit"><%= link_to "Cart", Cart.last, :class => "small-button"%></button>
          -->
          <%= link_to "", Cart.last, :class => "shopping-cart"%>

          <%=image_tag('white.jpg', alt: 'white', height: 10, width: 5) %>

        </form>
      </div>
    </nav>

    <div class="navigation-bar-container">
      <%=image_tag('white.jpg', alt: 'white', height: 75, width: 70) %>
    </div>

    <div class="navigation-bar-container">
      <ul>
        <li class="one navigation-bar-item"><%= link_to "Aisles", categories_index_path, class: "customized-btn"%></li>
        &nbsp;
        &nbsp;
        <li class="two navigation-bar-item"><%= link_to "History", history_index_path, class: "customized-btn"%></li>
        &nbsp;
        &nbsp;
        <li class="three navigation-bar-item"><%= link_to "Savings", savings_index_path, class: "customized-btn"%></li>
        &nbsp;
        &nbsp;
        <li class="three navigation-bar-item"><%= link_to "Recipes", recipe_index_path, class: "customized-btn"%></li>
      </ul>
    </div>

  </body>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

   <!-- HEADER -->

  <%= yield %>
</html>